name: verifier_app
description: The Citizen Zero Verifier App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  
  # Navigation
  go_router: ^12.0.0
  
  # Networking
  dio: ^5.3.0
  
  # Scanning
  mobile_scanner: ^3.5.0
  
  # UI
  google_fonts: ^6.1.0

  # Shared Packages
  citizen_zero_core:
    path: ../shared/citizen_zero_core
  citizen_zero_ui:
    path: ../shared/citizen_zero_ui
  citizen_zero_platform:
    path: ../shared/citizen_zero_platform

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
